drop table agency cascade;
drop table calendar cascade;
drop table frequencies cascade;
drop table routes cascade;
drop table shapes cascade;
drop table stop_times cascade;
drop table stops cascade;
drop table transfers cascade;
drop table trips cascade;
